---
- name: Restore SELinux labels
  become: true
  command:
    cmd: "restorecon -FRv {{ item }}"
  loop:
    - "/etc/ssh"
  when:
    - ssh_server_selinux_available
    - ssh_server_selinux_enabled

- name: Restart the SSH service
  become: true
  service:
    name:
      - sshd.service
    status: restarted
  when: ssh_server_restart_service